yatube/about/urls.py
from django.urls import path
from . import views

app_name = 'about'

urlpatterns = [
    path('author/', views.AboutAuthorView.as_view(), name='author'),
    path('tech/', views.AboutTechView.as_view(), name='tech'),
]

yatube/posts/urls.py
from django.urls import path
from . import views

app_name = 'posts'

urlpatterns = [
    # Посты
    path('', views.index, name='index'),
    path('posts/<int:post_id>/', views.post_detail, name='post_detail'),
    # По группам
    path('group/<slug:slug>/', views.group_posts, name='group_list'),
    # По пользователю
    path('profile/<str:username>/', views.profile, name='profile'),
    # Создание, редактирование и удаление постов
    path('create/', views.post_create, name='post_create'),
    path('posts/<int:post_id>/edit/', views.post_edit, name='post_edit'),
    path(
        'posts/<int:post_id>/delete/',
        views.post_delete,
        name='post_delete'
    ),
    # Подписки на авторов
    path('follow/', views.follow_index, name='follow_index'),
    path(
        'profile/<str:username>/follow/',
        views.profile_follow,
        name='profile_follow'
    ),
    path(
        'profile/<str:username>/unfollow/',
        views.profile_unfollow,
        name='profile_unfollow'
    ),
    # Комментарии
    path(
        'posts/<int:post_id>/comment/',
        views.add_comment,
        name='add_comment'
    ),
    path(
        'posts/<int:post_id>/comment/<int:comment_id>/delete/',
        views.comment_delete, name='comment_delete'
    ),
]

yatube/users/urls.py
from django.contrib.auth.views import (
    LoginView, LogoutView, PasswordChangeView, PasswordChangeDoneView,
    PasswordResetView, PasswordResetDoneView, PasswordResetConfirmView,
    PasswordResetCompleteView,
)
from django.urls import path
from . import views


app_name = 'users'

urlpatterns = [
    path(
        'logout/',
        LogoutView.as_view(
            template_name='users/logged_out.html'),
        name='logout'
    ),
    path('signup/', views.SignUp.as_view(), name='signup'),
    path(
        'login/',
        LoginView.as_view(template_name='users/login.html'),
        name='login'
    ),
    path(
        'password_change/',
        PasswordChangeView.as_view(
            template_name='users/password_change_form.html'),
        name='password_change'
    ),
    path(
        'password_change/done/',
        PasswordChangeDoneView.as_view(
            template_name='users/password_change_done.html'),
        name='password_change_done'
    ),
    path(
        'password_reset/',
        PasswordResetView.as_view(
            template_name='users/password_reset_form.html'),
        name='password_reset_form'
    ),
    path(
        'password_reset/done/',
        PasswordResetDoneView.as_view(
            template_name='users/password_reset_done.html'),
        name='password_reset_done'
    ),
    path(
        'reset/<uidb64>/<token>/',
        PasswordResetConfirmView.as_view(
            template_name='users/password_reset_confirm.html'),
        name='password_reset_confirm'
    ),
    path(
        'reset/done/',
        PasswordResetCompleteView.as_view(
            template_name='users/password_reset_complete.html'),
        name='password_reset_complete'
    ),
]

yatube/yatube/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('', include('posts.urls', namespace='posts')),
    path('admin/', admin.site.urls),
    path('auth/', include('users.urls', namespace='users')),
    path('auth/', include('django.contrib.auth.urls')),
    path('about/', include('about.urls', namespace='about')),
]

handler404 = 'core.views.page_not_found'
handler403 = 'core.views.permission_denied'
handler500 = 'core.views.server_error'

if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )

if settings.DEBUG:
    import debug_toolbar
    urlpatterns += (
        path('__debug__/', include(debug_toolbar.urls)),
    )

yatube/templates/includes/comment.html
{% load user_filters %}
{% if post.comments.count != 0  %}
  <!-- Акоордеон с комментариями по умолчанию свернут -->
  <div class="accordion" id="accordionExample">
    <div class="accordion-item">
      <h2 class="accordion-header" id="heading{{ post.id }}">
        <button class="accordion-button collapsed" type="button"
          data-bs-toggle="collapse" data-bs-target="#collapse{{ post.id }}"
          aria-expanded="false" aria-controls="collapse{{ post.id }}">
            Комментарии ({{ post.comments.count }}):
        </button>
      </h2>
      <div id="collapse{{ post.id }}" class="accordion-collapse collapse"
        aria-labelledby="heading{{ post.id }}" style="">
        <div class="accordion-body">
          <ul class="list-group list-group-flush">
            {% for comment in comments %}
              {% if post == comment.post %}
                <li class="list-group-item">
                  <div class="row">
                    <aside class="col-12 col-md-3">
                      <a href="{% url 'posts:profile' comment.author.username %}">
                        {{ comment.author.username }}
                      </a>
                      <br>
                      <small>
                        ({{ comment.created }})
                      </small>
                    </aside>
                    <article class="col-12 col-md-9">
                      {{ comment.text|linebreaks }}
                    </article>
                  </div>
                </li>
              {% endif %}
            {% endfor %}
          </ul>
        </div>
      </div>
    </div>
</div>
{% endif %}

yatube/templates/includes/errors_check.html
{% if form.errors %}
{% for field in form %}
  {% for error in field.errors %}            
    <div class="alert alert-danger">
      {{ error|escape }}
    </div>
  {% endfor %}
{% endfor %}
{% for error in form.non_field_errors %}
  <div class="alert alert-danger">
    {{ error|escape }}
  </div>
{% endfor %}
{% endif %}

yatube/templates/includes/footer.html
<footer class="border-top text-center py-3">
  <p>© {{ year }} Copyright <span style="color:red">Ya</span>tube</p> 
</footer>   

yatube/templates/includes/form_render.html
{% load user_filters %}
{% csrf_token %}
{% for field in form %}
  <div class="form-group row my-3"
    {% if field.field.required %} 
      aria-required="true"
    {% else %}
      aria-required="false"
    {% endif %}
  >
    <label for="{{ field.id_for_label }}">
      {{ field.label }}
        {% if field.field.required %}
          <span class="required text-danger">*</span>
        {% endif %}
    </label>
    <div>
    {{ field|addclass:'form-control' }}
      {% if field.help_text %}
        <small id="{{ field.id_for_label }}-help" class="form-text text-muted">
          {{ field.help_text|safe }}
        </small>
      {% endif %}
    </div>
  </div>
{% endfor %}

yatube/templates/includes/header.html
{% load static %}
{% with request.resolver_match.view_name as view_name %}
<header>
  <nav class="navbar navbar-expand-lg navbar-light"
    style="background-color: lightskyblue">
    <div class="container">
      <a class="navbar-brand" href="{% url 'posts:index' %}">
      <img src="{% static 'img/logo.png' %}" width="30" height="30" 
        class="d-inline-block align-top" alt="">
      <span style="color:red">Ya</span>tube</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse"
        data-bs-target="#navbarSupportedContent"
        aria-controls="navbarSupportedContent"
        aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav nav-pills ms-auto mb-2 mb-lg-0">
          <li class="nav-item"> 
            <a class="nav-link
              {% if view_name  == 'about:author' %}active{% endif %}"
              href="{% url 'about:author' %}">
                Об авторе
              </a>
          </li>
          <li class="nav-item">
            <a class="nav-link
              {% if view_name  == 'about:tech' %}active{% endif %}"
              href="{% url 'about:tech' %}">
                Технологии
              </a>
          </li>
          {% if user.is_authenticated %}
          <li class="nav-item"> 
            <a class="nav-link
              {% if view_name  == 'posts:post_create' %}active{% endif %}"
              href="{% url 'posts:post_create' %}">
                Новая запись
              </a>
          </li>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle link-dark"
              id="navbarDropdown" role="button"
              data-bs-toggle="dropdown" aria-expanded="false">
              Пользователь: {{ user.username }}
            </a>
            <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
              <li>
                <a class="dropdown-item"
                href="{% url 'users:password_change' %}">
                  Изменить пароль
                </a>
              </li>
              <li>
                <a class="dropdown-item"
                href="{% url 'users:logout' %}">
                  Выйти
                </a>
              </li>
            </ul>
          </li>
          {% else %}
          <li class="nav-item"> 
            <a class="nav-link link-light
              {% if view_name  == 'users:login' %}active{% endif %}"
              href="{% url 'users:login' %}">
                Войти
              </a>
          </li>
          <li class="nav-item"> 
            <a class="nav-link link-light
              {% if view_name  == 'users:signup' %}active{% endif %}"
              href="{% url 'users:signup' %}">
                Регистрация
              </a>
          </li>
          {% endif %}
        </ul>
      </div>
    </div>
  </nav>
</header>
{% endwith %} 

yatube/templates/includes/paginator.html
{% if page_obj.has_other_pages %}
<nav aria-label="Page navigation" class="my-5">
  <ul class="pagination">
    {% if page_obj.has_previous %}
      <li class="page-item"><a class="page-link" href="?page=1">Первая</a></li>
      <li class="page-item">
        <a class="page-link" href="?page={{ page_obj.previous_page_number }}">
          Предыдущая
        </a>
      </li>
    {% endif %}
    {% for i in page_obj.paginator.page_range %}
        {% if page_obj.number == i %}
          <li class="page-item active">
            <span class="page-link">{{ i }}</span>
          </li>
        {% else %}
          <li class="page-item">
            <a class="page-link" href="?page={{ i }}">{{ i }}</a>
          </li>
        {% endif %}
    {% endfor %}
    {% if page_obj.has_next %}
      <li class="page-item">
        <a class="page-link" href="?page={{ page_obj.next_page_number }}">
          Следующая
        </a>
      </li>
      <li class="page-item">
        <a class="page-link" href="?page={{ page_obj.paginator.num_pages }}">
          Последняя
        </a>
      </li>
    {% endif %}    
  </ul>
</nav>
{% endif %}

yatube/templates/includes/post_card.html
{% load thumbnail %}
<article>
  <div class="card bg-light mb-3">
    <div class="card-body">
      <ul>
        {% if not is_profile %}
        <li>
          Автор: 
          <a href="{% url 'posts:profile' post.author.username %}">{{ post.author.get_full_name }}</a>
        </li>
        {% endif %}
        {% if not is_group %}
          {% if post.group %}
          <li>
            Группа:
            <a href="{% url 'posts:group_list' post.group.slug %}">{{ post.group.title }}</a>
          </li>
          {% endif %}
        {% endif %}
        <li>
          Дата публикации: {{ post.pub_date|date:"d E Y" }}
        </li>
      </ul>      
      {% thumbnail post.image "960x339" crop="top" upscale=True as im %}
        <img class="card-img my-2" src="{{ im.url }}">
      {% endthumbnail %}
      <p>{{ post.text|linebreaks }}</p>
      <!-- Группа кнопок-ссылок после текста поста -->
      <a class="btn btn-outline-secondary my-3"
        href="{% url 'posts:post_detail' post.pk %}">
          Страница поста
      </a>
      {% if not is_profile %}
        <a class="btn btn-outline-secondary my-3"
        href="{% url 'posts:profile' post.author.username %}">
          Все посты автора
        </a>
      {% endif %}
      {% if not is_group %}
        {% if post.group %}
          <a class="btn btn-outline-secondary my-3"
          href="{% url 'posts:group_list' post.group.slug %}">
            Все посты группы
          </a>
        {% endif %}
      {% endif %}
      <!-- Инклюд с комментариями -->
      {% include 'includes/comment.html' %}
    </div>
  </div>
</article>

yatube/templates/includes/switcher.html
{% if user.is_authenticated %}
  <div class="row my-3">
    <ul class="nav nav-tabs">
      <li class="nav-item">
        <a 
          class="nav-link {% if is_index %}active{% endif %}"
          href="{% url 'posts:index' %}"
        >
          Все авторы
        </a>
      </li>
      <li class="nav-item">
        <a 
           class="nav-link {% if is_follow %}active{% endif %}"
           href="{% url 'posts:follow_index' %}"
        >
          Избранные авторы
        </a>
      </li>
    </ul>
  </div>
{% endif %}