yatube/about/urls.py
from django.urls import path
from . import views

app_name = 'about'

urlpatterns = [
    path('author/', views.AboutAuthorView.as_view(), name='author'),
    path('tech/', views.AboutTechView.as_view(), name='tech'),
]

yatube/posts/urls.py
from django.urls import path
from . import views

app_name = 'posts'

urlpatterns = [
    # Посты
    path('', views.index, name='index'),
    path('posts/<int:post_id>/', views.post_detail, name='post_detail'),
    # По группам
    path('group/<slug:slug>/', views.group_posts, name='group_list'),
    # По пользователю
    path('profile/<str:username>/', views.profile, name='profile'),
    # Создание, редактирование и удаление постов
    path('create/', views.post_create, name='post_create'),
    path('posts/<int:post_id>/edit/', views.post_edit, name='post_edit'),
    path(
        'posts/<int:post_id>/delete/',
        views.post_delete,
        name='post_delete'
    ),
    # Подписки на авторов
    path('follow/', views.follow_index, name='follow_index'),
    path(
        'profile/<str:username>/follow/',
        views.profile_follow,
        name='profile_follow'
    ),
    path(
        'profile/<str:username>/unfollow/',
        views.profile_unfollow,
        name='profile_unfollow'
    ),
    # Комментарии
    path(
        'posts/<int:post_id>/comment/',
        views.add_comment,
        name='add_comment'
    ),
    path(
        'posts/<int:post_id>/comment/<int:comment_id>/delete/',
        views.comment_delete, name='comment_delete'
    ),
]

yatube/yatube/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('', include('posts.urls', namespace='posts')),
    path('admin/', admin.site.urls),
    path('auth/', include('users.urls', namespace='users')),
    path('auth/', include('django.contrib.auth.urls')),
    path('about/', include('about.urls', namespace='about')),
]

handler404 = 'core.views.page_not_found'
handler403 = 'core.views.permission_denied'
handler500 = 'core.views.server_error'

if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )

if settings.DEBUG:
    import debug_toolbar
    urlpatterns += (
        path('__debug__/', include(debug_toolbar.urls)),
    )

yatube/posts/models.py
from django.db import models
from django.contrib.auth import get_user_model

User = get_user_model()


class Group(models.Model):
    title = models.CharField(max_length=200)
    slug = models.SlugField(unique=True)
    description = models.TextField(
        blank=True,
        null=True
    )

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = 'Группа'
        verbose_name_plural = 'Группы'


class Post(models.Model):
    text = models.TextField(
        'Текст',
        help_text='Текст нового поста',
    )
    pub_date = models.DateTimeField(
        'Дата публикации',
        auto_now_add=True
    )
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='posts',
        verbose_name='Автор',
    )
    group = models.ForeignKey(
        Group,
        blank=True,
        null=True,
        on_delete=models.SET_NULL,
        related_name='posts',
        verbose_name='Группа',
        help_text='Группа, к которой будет относиться пост',
    )
    image = models.ImageField(
        'Картинка',
        upload_to='posts/',
        blank=True
    )

    def __str__(self):
        return (self.text)[:15]

    class Meta:
        ordering = ['-pub_date']
        verbose_name = 'Пост'
        verbose_name_plural = 'Посты'


class Comment(models.Model):
    text = models.TextField(
        'Комментарий',
        help_text='Текст комментария',
    )
    post = models.ForeignKey(
        Post,
        on_delete=models.CASCADE,
        related_name='comments',
        verbose_name='Пост',
        help_text='Пост, к которому относится комментарий',
    )
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='comments',
        verbose_name='Автор комментария'
    )
    created = models.DateTimeField(
        'Комментарий создан',
        auto_now_add=True,
    )

    def __str__(self):
        return (self.text)[:15]

    class Meta:
        ordering = ['-created']
        verbose_name = 'Комментарий'
        verbose_name_plural = 'Комментарии'


class Follow(models.Model):
    user = models.ForeignKey(
        User,
        blank=True,
        null=True,
        on_delete=models.CASCADE,
        related_name='follower',
        verbose_name='Подписчик'
    )
    author = models.ForeignKey(
        User,
        blank=True,
        null=True,
        on_delete=models.CASCADE,
        related_name='following',
        verbose_name='Автор контента'
    )

    def __str__(self):
        return f'{self.user.username} - {self.author.username}'

    class Meta:
        verbose_name = 'Подписка на авторов'
        verbose_name_plural = 'Подписки на авторов'
        constraints = [
            models.UniqueConstraint(
                fields=['user', 'author'],
                name='unique_following'
            )
        ]

yatube/posts/forms.py
from django import forms
from .models import Post, Comment


class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ('text', 'image', 'group')


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('text',)

yatube/posts/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import get_object_or_404, render, redirect
from .forms import PostForm, CommentForm
from .models import Follow, Post, Group, User, Comment
from .utils import posts_on_page
from django.views.decorators.cache import cache_page
from django.core.cache import cache


@cache_page(20, key_prefix='index_page')
def index(request):
    """Главная страница - список постов."""
    posts = Post.objects.all().select_related('author', 'group')
    comments = Comment.objects.all().select_related('post', 'author')
    page_obj = posts_on_page(request, posts)
    return render(
        request,
        'posts/index.html',
        {'page_obj': page_obj, 'comments': comments,
         'is_index': True}
    )


def group_posts(request, slug):
    """Страница с постами одной группы."""
    group = get_object_or_404(Group, slug=slug)
    posts = group.posts.all().select_related('author', 'group'
                                             ).order_by('pub_date')
    page_obj = posts_on_page(request, posts)
    comments = Comment.objects.all().select_related('post', 'author')
    return render(
        request,
        'posts/group_list.html',
        {'group': group, 'page_obj': page_obj,
         'comments': comments, 'is_group': True}
    )


def profile(request, username):
    """Список постов одного автора с подпиской на автора."""
    author = get_object_or_404(User, username=username)
    posts = author.posts.all().select_related('author', 'group')
    page_obj = posts_on_page(request, posts)
    following = (
        request.user.is_authenticated and request.user.follower.filter(
            user=request.user,
            author=author
        ).exists()
    )
    comments = Comment.objects.all().select_related('post', 'author')
    return render(
        request,
        'posts/profile.html',
        {'page_obj': page_obj, 'author': author, 'comments': comments,
         'is_profile': True, 'following': following}
    )


@login_required
def add_comment(request, post_id):
    """Добавление комментария к посту."""
    form = CommentForm(request.POST or None)
    if form.is_valid():
        comment = form.save(commit=False)
        comment.author = request.user
        comment.post = get_object_or_404(Post, pk=post_id)
        comment.save()
    return redirect('posts:post_detail', post_id=post_id)


def post_detail(request, post_id):
    """Страница одного поста с добавлением комментариев и редактированием."""
    post = get_object_or_404(Post, pk=post_id)
    comments = post.comments.all().select_related('author', 'post')
    form = CommentForm()
    return render(
        request,
        'posts/post_detail.html',
        {'post': post, 'comments': comments, 'form': form}
    )


@login_required
def post_create(request):
    """Форма создания нового поста."""
    if request.method == 'POST':
        form = PostForm(
            request.POST or None,
            files=request.FILES or None
        )
        if form.is_valid():
            post = form.save(commit=False)
            post.author = request.user
            post.save()
            return redirect('posts:profile', post.author.username)
        return render(
            request,
            'posts/create_post.html',
            {'form': form}
        )
    form = PostForm()
    return render(
        request,
        'posts/create_post.html',
        {'form': form}
    )


@login_required
def post_edit(request, post_id):
    """Форма редактирования поста."""
    post = get_object_or_404(Post, pk=post_id)
    if post.author == request.user:
        if request.method == 'POST':
            form = PostForm(
                request.POST or None,
                files=request.FILES or None,
                instance=post
            )
            if form.is_valid():
                form.save()
                return redirect('posts:post_detail', post_id)
            return render(
                request,
                'posts/create_post.html',
                {'form': form, 'is_edit': True}
            )
        form = PostForm(instance=post)
        return render(
            request,
            'posts/create_post.html',
            {'form': form, 'is_edit': True}
        )
    return redirect('posts:post_detail', post_id)


@login_required
def follow_index(request):
    """Список постов авторов на которых подписан."""
    posts = Post.objects.filter(
        author__following__user=request.user
    ).select_related('author', 'group')
    page_obj = posts_on_page(request, posts)
    comments = Comment.objects.all().select_related('post', 'author')
    return render(
        request,
        'posts/follow.html',
        {'page_obj': page_obj, 'is_follow': True, 'comments': comments}
    )


@login_required
def profile_follow(request, username):
    """Подписка на автора."""
    author = get_object_or_404(User, username=username)
    following = Follow.objects.filter(user=request.user, author=author)
    if author == request.user or following.exists():
        return redirect('posts:profile', author.username)
    Follow.objects.create(user=request.user, author=author)
    return redirect('posts:profile', author.username)


@login_required
def profile_unfollow(request, username):
    """Отписка от автора."""
    author = get_object_or_404(User, username=username)
    following = Follow.objects.filter(user=request.user, author=author)
    if following.exists():
        following.delete()
    return redirect('posts:profile', author.username)


@login_required
def post_delete(request, post_id):
    """Удаление поста."""
    post = get_object_or_404(Post, pk=post_id)
    if request.user == post.author:
        post.delete()
        cache.clear()
    return redirect('posts:profile', username=request.user)


@login_required
def comment_delete(request, post_id, comment_id):
    """Удаление комментария."""
    comment = get_object_or_404(Comment, pk=comment_id)
    if request.user == comment.author:
        comment.delete()
    return redirect('posts:post_detail', post_id=post_id)

yatube/templates/posts/create_post.html
{% extends 'base.html' %}
{% load thumbnail %}

{% block title %}
  {% if is_edit %}
    Редактировать запись
  {% else %}
    Добавить запись
  {% endif %}
{% endblock %}

{% block content %}
  <div class="row justify-content-center">
    <div class="col-md-8 p-5">
      <div class="card">
        <div class="card-header">
          {% if is_edit %}
            Редактировать запись
          {% else %}
            Добавить запись
          {% endif %}      
        </div>
        <div class="card-body">
          {% include 'includes/errors_check.html' %}
          {% if is_edit %}
          <form method="post" enctype="multipart/form-data">
          {% else %}
          <form method="post" enctype="multipart/form-data" action="{% url 'posts:post_create' %}">
          {% endif %}
            {% include 'includes/form_render.html' %}
            <div class="col-md-6 offset-md-4">
              <button type="submit" class="btn btn-secondary">
                {% if is_edit %}
                  Сохранить
                {% else %}
                  Добавить
                {% endif %}
              </button>
            </div>
          </form>
        </div>
      </div>
    </div>
  </div>
{% endblock %}

yatube/templates/posts/follow.html
{% extends 'base.html' %}

{% block title %}    
  Лента постов
{% endblock %}

{% block content %}
<h1>Лента постов</h1>
{% include 'includes/switcher.html' %}
  {% for post in page_obj %}
    {% include 'includes/post_card.html' %}
  {% endfor %}
{% endblock %} 

yatube/templates/posts/group_list.html
{% extends 'base.html' %}

{% block title %}    
  {{ group.title }}
{% endblock %}

{% block content %}
  <h1>
    {{ group.title }}
  </h1>
  <p>
    {{ group.description }}
  </p>
  {% for post in page_obj %}
    {% include 'includes/post_card.html' %}
  {% endfor %}
{% endblock %} 

yatube/templates/posts/index.html
{% extends 'base.html' %}

{% block title %}    
  Лента постов
{% endblock %}

{% block content %}
<h1>Лента постов</h1>
{% include 'includes/switcher.html' %}
  {% for post in page_obj %}
    {% include 'includes/post_card.html' %}
  {% endfor %}
{% endblock %} 

yatube/templates/posts/post_detail.html
{% extends 'base.html' %}
{% load thumbnail %}
{% load user_filters %}

{% block title %}    
  {{ post|truncatechars:30 }}
{% endblock %}

{% block content %}
  <div class="row">
    <aside class="col-12 col-md-3">
      <ul class="list-group list-group-flush">
        <li class="list-group-item">
          Дата публикации: {{ post.pub_date|date:"d E Y" }} 
        </li>
        {% if post.group %}
          <li class="list-group-item">
            Группа:
            <a href="{% url 'posts:group_list' post.group.slug %}">
              {{ post.group.title }}
            </a>
          </li>
        {% endif %}
        <li class="list-group-item">
          Автор:
          <a href="{% url 'posts:profile' post.author.username %}">
            {{ post.author.get_full_name }} </a> ({{ post.author.username }})
        </li>
        <li class="list-group-item d-flex justify-content-between align-items-center">
          Всего постов автора:  <span >{{ post.author.posts.count}}</span>
        </li>
      </ul>
    </aside>
    <article class="col-12 col-md-9">
      <div class="card bg-light mb-3">
        <div class="card-body">
          {% thumbnail post.image "960x339" crop="top" upscale=True as im %}
            <img class="card-img my-2" src="{{ im.url }}">
          {% endthumbnail %}
          <p>
            {{ post.text|linebreaks }}
          </p>
          <!-- Группа кнопок-ссылок после текста поста -->
          {% if not is_profile %}
            <a class="btn btn-outline-secondary my-3"
              href="{% url 'posts:profile' post.author.username %}">
              Все посты автора
            </a>
          {% endif %}
          {% if not is_group %}
            {% if post.group %}
              <a class="btn btn-outline-secondary my-3"
                href="{% url 'posts:group_list' post.group.slug %}">
                Все посты группы
              </a>
            {% endif %}
          {% endif %}
          {% if post.author == user %}
            <a class="btn btn-outline-secondary my-3"
              href="{% url 'posts:post_edit' post.pk %}">
              Редактировать пост
            </a>
            <button type="button" class="btn btn-outline-secondary"
              data-bs-toggle="modal" data-bs-target="#modal1">
                Удалить пост
            </button>
          {% endif %}
          <!-- Форма добавление комментария -->
          {% if user.is_authenticated %}
            <div class="card my-4">
              <h5 class="card-header">Добавить комментарий:</h5>
              <div class="card-body">
                <form method="post"
                  action="{% url 'posts:add_comment' post.id %}">
                  {% csrf_token %}      
                  <div class="form-group mb-2">
                    {{ form.text|addclass:"form-control" }}
                  </div>
                  <button type="submit" class="btn btn-secondary">
                    Отправить
                  </button>
                </form>
              </div>
            </div>
          {% endif %}
          <!-- Аккордеон со списком комментариев, по умолчанию развернут -->
          {% if post.comments.count != 0  %}
            <div class="accordion" id="accordionExample">
              <div class="accordion-item">
                <h2 class="accordion-header" id="heading{{ post.id }}">
                  <button class="accordion-button" type="button"
                    data-bs-toggle="collapse"
                    data-bs-target="#collapse{{ post.id }}"
                    aria-expanded="false"
                    aria-controls="collapse{{ post.id }}"
                    >
                      Комментарии ({{ post.comments.count }}):
                  </button>
                </h2>
                <div id="collapse{{ post.id }}"
                  class="accordion-collapse collapse show"
                  aria-labelledby="heading{{ post.id }}" style=""
                  >
                  <div class="accordion-body">
                    <ul class="list-group list-group-flush">
                      {% for comment in comments %}
                        {% if post == comment.post %}
                          <li class="list-group-item">
                            <div class="row">
                              <!-- Слева имя автора комментария -->
                              <aside class="col-12 col-md-3">
                                <a href="{% url 'posts:profile' comment.author.username %}">
                                  {{ comment.author.username }}
                                </a><br> <small>({{ comment.created }})</small>
                                {% if comment.author == user %}
                                  <button type="button" class="btn btn-outline-secondary btn-sm my-1"
                                    data-bs-toggle="modal" data-bs-target="#modal2">
                                      удалить
                                  </button>
                                {% endif %}
                              </aside>
                              <!-- Справа текст комментария -->
                              <article class="col-12 col-md-9">
                                {{ comment.text|linebreaks }}
                              </article>
                            </li>
                        {% endif %}
                        <!-- Окно подтверждения удаления комментария -->
                        <div class="modal fade" id="modal2" tabindex="-1">
                          <div class="modal-dialog">
                            <div class="modal-content">
                              <div class="modal-header">
                                <h5 class="modal-title">Требуется подтверждение</h5>
                                <button type="button" class="btn-close" data-bs-dismiss="modal"></button>
                              </div>
                              <div class="modal-body">
                                <p>Вы уверены, что хотите удалить комментарий? Восстановить его будет невозможно!</p>
                              </div>
                              <div class="modal-footer">
                                <a class="btn btn-danger my-3"
                                  href="{% url 'posts:comment_delete' comment.post.pk comment.pk %}">
                                    Да, я уверен!
                                  </a>
                                <a class="btn btn-secondary my-3" data-bs-dismiss="modal">
                                    Нет, я передумал.
                                </a>
                              </div>
                            </div>
                          </div>
                        </div>
                      {% endfor %}
                    </ul>
                  </div>
                </div>
              </div>
            </div>
          {% endif %}
          <!-- Конец аккордеона -->
        </div>
      </div>
    </article>
  </div>
  <!-- Окно подтверждения удаления поста -->
  <div class="modal fade" id="modal1" tabindex="-1">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title">Требуется подтверждение</h5>
          <button type="button" class="btn-close" data-bs-dismiss="modal"></button>
        </div>
        <div class="modal-body">
          <p>Вы уверены, что хотите удалить пост? Восстановить его будет невозможно!</p>
        </div>
        <div class="modal-footer">
          <a class="btn btn-danger my-3"
            href="{% url 'posts:post_delete' post.pk %}">
              Да, я уверен!
            </a>
          <a class="btn btn-secondary my-3" data-bs-dismiss="modal">
              Нет, я передумал.
          </a>
        </div>
      </div>
    </div>
  </div>
{% endblock %} 

yatube/templates/posts/profile.html
{% extends 'base.html' %}

{% block title %}    
  Профайл автора {{ author.get_full_name }}
{% endblock %}

{% block content %}
<h1>
  Все посты автора: {{ author.get_full_name }}
  {% if user.is_authenticated and author != user %}
  {% if following %}
    <a
      class="btn btn-outline-secondary"
      href="{% url 'posts:profile_unfollow' author.username %}" role="button"
    >
      Отписаться
    </a>
  {% else %}
    <a
      class="btn btn-secondary"
      href="{% url 'posts:profile_follow' author.username %}" role="button"
    >
      Подписаться
    </a>
  {% endif %}
{% endif %}
</h1>
<h3>
  Всего постов: {{ author.posts.count }}
</h3>
{% for post in page_obj %}
{% include 'includes/post_card.html' %}
{% comment %} {% if not forloop.last %}<hr>{% endif %} {% endcomment %}
{% endfor %}
{% endblock %} 