yatube/about/urls.py
from django.urls import path
from . import views

app_name = 'about'

urlpatterns = [
    path('author/', views.AboutAuthorView.as_view(), name='author'),
    path('tech/', views.AboutTechView.as_view(), name='tech'),
]

yatube/users/urls.py
from django.contrib.auth.views import (
    LoginView, LogoutView, PasswordChangeView, PasswordChangeDoneView,
    PasswordResetView, PasswordResetDoneView, PasswordResetConfirmView,
    PasswordResetCompleteView,
)
from django.urls import path
from . import views


app_name = 'users'

urlpatterns = [
    path(
        'logout/',
        LogoutView.as_view(
            template_name='users/logged_out.html'),
        name='logout'
    ),
    path('signup/', views.SignUp.as_view(), name='signup'),
    path(
        'login/',
        LoginView.as_view(template_name='users/login.html'),
        name='login'
    ),
    path(
        'password_change/',
        PasswordChangeView.as_view(
            template_name='users/password_change_form.html'),
        name='password_change'
    ),
    path(
        'password_change/done/',
        PasswordChangeDoneView.as_view(
            template_name='users/password_change_done.html'),
        name='password_change_done'
    ),
    path(
        'password_reset/',
        PasswordResetView.as_view(
            template_name='users/password_reset_form.html'),
        name='password_reset_form'
    ),
    path(
        'password_reset/done/',
        PasswordResetDoneView.as_view(
            template_name='users/password_reset_done.html'),
        name='password_reset_done'
    ),
    path(
        'reset/<uidb64>/<token>/',
        PasswordResetConfirmView.as_view(
            template_name='users/password_reset_confirm.html'),
        name='password_reset_confirm'
    ),
    path(
        'reset/done/',
        PasswordResetCompleteView.as_view(
            template_name='users/password_reset_complete.html'),
        name='password_reset_complete'
    ),
]

yatube/yatube/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('', include('posts.urls', namespace='posts')),
    path('admin/', admin.site.urls),
    path('auth/', include('users.urls', namespace='users')),
    path('auth/', include('django.contrib.auth.urls')),
    path('about/', include('about.urls', namespace='about')),
]

handler404 = 'core.views.page_not_found'
handler403 = 'core.views.permission_denied'
handler500 = 'core.views.server_error'

if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )

if settings.DEBUG:
    import debug_toolbar
    urlpatterns += (
        path('__debug__/', include(debug_toolbar.urls)),
    )

yatube/users/forms.py
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import get_user_model


User = get_user_model()


class CreationForm(UserCreationForm):
    class Meta(UserCreationForm.Meta):
        model = User
        fields = ('first_name', 'last_name', 'username', 'email')

yatube/users/views.py
from django.views.generic import CreateView
from django.urls import reverse_lazy

from .forms import CreationForm


class SignUp(CreateView):
    form_class = CreationForm
    success_url = reverse_lazy('posts:index')
    template_name = 'users/signup.html'

yatube/templates/users/logged_out.html
{% extends 'base.html' %}

{% block title %}
  Вы вышли из системы
{% endblock %}

{% block content %}
  <div class="row justify-content-center">
    <div class="col-md-8 p-5">
      <div class="card">
        <div class="card-header">
          Выход
        </div>
        <div class="card-body">
          <p>
            Вы вышли из своей учётной записи. Ждём вас снова!
          </p>
        </div>
      </div>
    </div>
  </div>
{% endblock %} 

yatube/templates/users/login.html
{% extends "base.html" %}

{% block title %}
  Войти
{% endblock %}

{% block content %}
  <div class="row justify-content-center">
    <div class="col-md-8 p-5">
      <div class="card">
        <div class="card-header">
          Войти на сайт
        </div>
        <div class="card-body">
          {% include 'includes/errors_check.html' %}
          <form method="post"
            {% if action_url %}
              action="{% url 'users:login' %}"
            {% endif %}
          >          
            {% include 'includes/form_render.html' %}  
            <div class="col-md-6 offset-md-4">
              <button type="submit" class="btn btn-primary">
                Войти
              </button>
              <a href="{% url 'users:password_reset_form' %}" class="btn btn-link">
                Забыли пароль?
              </a>
            </div>
          </form>
        </div>
      </div>
    </div>
  </div>
{% endblock %}

yatube/templates/users/password_change_done.html
{% extends 'base.html' %}

{% block title %}
  Пароль изменен
{% endblock %}

{% block content %}
  <div class="row justify-content-center">
    <div class="col-md-8 p-5">
      <div class="card">
        <div class="card-header">
          Пароль изменён
        </div>
        <div class="card-body"> 
          <p>Пароль изменён успешно</p>
        </div>
      </div>
    </div>
  </div>
{% endblock %} 

yatube/templates/users/password_change_form.html
{% extends 'base.html' %}

{% block title %}
  Изменение пароля
{% endblock %}

{% block content %}
{% load user_filters %} 
  <div class="row justify-content-center">
    <div class="col-md-8 p-5">
      <div class="card">
        <div class="card-header">
          Изменить пароль
        </div>
        <div class="card-body">
          {% include 'includes/errors_check.html' %}
          <form method="post" action="{% url 'users:password_change' %}">  
            {% include 'includes/form_render.html' %}
            <div class="col-md-6 offset-md-4">
              <button type="submit" class="btn btn-primary">
                Изменить пароль
              </button>
            </div>
          </form>
        </div>
      </div>
    </div>
  </div>
{% endblock %}

yatube/templates/users/password_reset_complete.html
{% extends 'base.html' %}

{% block title %}
  Сброс пароля прошел успешно
{% endblock %}

{% block content %}
  <div class="row justify-content-center">
    <div class="col-md-8 p-5">
      <div class="card">
        <div class="card-header">
          Восстановление пароля завершено
        </div>
        <div class="card-body"> 
          <p>Ваш пароль был сохранен. Используйте его для входа</p>
        </div>
      </div>
    </div>
  </div>
{% endblock %} 

yatube/templates/users/password_reset_confirm.html
{% extends "base.html" %}

{% block title %}
  Новый пароль
{% endblock %}

{% block content %}
  {% if validlink %}
    <div class="row justify-content-center">
      <div class="col-md-8 p-5">
        <div class="card">
          <div class="card-header">
            Изменить пароль
          </div>
          <div class="card-body">
            {% include 'includes/errors_check.html' %}
            <form method="post">
              {% include 'includes/form_render.html' %}
              <div class="col-md-6 offset-md-4">
                <button type="submit" class="btn btn-primary">
                  Изменить пароль
                </button>
              </div>
            </form>
          </div>
        </div>
      </div>
    </div>
  {% else %}
    <div class="row justify-content-center">
      <div class="col-md-8 p-5">
        <div class="card">
          <div class="card-header">Ошибка</div>
          <div class="card-body">
            <p>Ссылка сброса пароля содержит ошибку или устарела.</p>
          </div>
        </div>
      </div>
    </div>
  {% endif %}
{% endblock %} 

yatube/templates/users/password_reset_done.html
{% extends 'base.html' %}

{% block title %}
  Сброс пароля прошел успешно
{% endblock %}

{% block content %}
  <div class="row justify-content-center">
    <div class="col-md-8 p-5">
      <div class="card">
        <div class="card-header">
          Отправлено письмо
        </div>
        <div class="card-body"> 
          <p>Проверьте свою почту, вам должно прийти письмо со ссылкой для восстановления пароля</p>
        </div>
      </div>
    </div>
  </div>
{% endblock %} 

yatube/templates/users/password_reset_form.html
{% extends 'base.html' %}

{% block title %}
  Сброс пароля
{% endblock %}

{% block content %}
  <div class="row justify-content-center">
    <div class="col-md-8 p-5">
      <div class="card">
        <div class="card-header">
          Чтобы сбросить старый пароль — введите адрес электронной почты, под которым вы регистрировались
        </div>
        <div class="card-body">
          {% include 'includes/errors_check.html' %}
          <form method="post" action="{% url 'users:password_reset_form' %}">
            {% include 'includes/form_render.html' %}
            <div class="col-md-6 offset-md-4">
              <button type="submit" class="btn btn-primary">
                сбросить пароль
              </button>
            </div>
          </form>
        </div>
      </div>
    </div>
  </div>
{% endblock %}

yatube/templates/users/signup.html
{% extends "base.html" %}

{% block title %}
  Зарегистрироваться
{% endblock %}

{% block content %}
  <div class="row justify-content-center">
    <div class="col-md-8 p-5">
      <div class="card">
        <div class="card-header">Зарегистрироваться</div>
          <div class="card-body">
            {% include 'includes/errors_check.html' %}
            <form method="post" action="{% url 'users:signup' %}">
              {% include 'includes/form_render.html' %}
              <div class="col-md-6 offset-md-4">
                <button type="submit" class="btn btn-primary">
                  Зарегистрироваться
                </button>
              </div>
            </form>
          </div>
        </div>
      </div>
  </div>
{% endblock %}